### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheJaredWilcurt** [elegantweb/nwjs-vue#1]
Tried `npm install` on Node v5.9.1 and it failed with `cb() never called`.

Tried `npm install` on Node v8.1.3 and it completed.

Tried `npm run dev` and got:

![npm run dev error](https://user-images.githubusercontent.com/4629794/30117416-245f094a-92ee-11e7-88bb-af9739d5a34d.png)

Tried `npm run build` and got:

![npm run build error](https://user-images.githubusercontent.com/4629794/30117422-2ba5699c-92ee-11e7-8721-7b68075e06c5.png)

Initial settings only disabled `vuex`.

**Comment by ghost** [comment]
Hi
For the second problem:
We have two `package.json` in the boilerplate, you need to also run `npm install` on the application directory.
```
cd app
npm install
```

**Comment by TheJaredWilcurt** [comment]
Tried that, it did not generate a `node_modules`

**Comment by ghost** [comment]
Yes cause you don't have any dependency in the `app/package.json`, I am fixing this.

**Comment by ghost** [comment]
For the first problem ensure that the file `/node_modules/.bin/run` exists.

**Comment by TheJaredWilcurt** [comment]
I've deleted the cached version from `C:\Users\jwilcurt\.vue-templates` and deleted the `nwvue-test` folder and started over.

The `nwvue-test/app/package.json` file still contains no deps or devDeps. So whatever you fixed didn't work. And running `npm install` in the directory won't do anything because of that.

Same issue with `run` not existing running `npm run dev`. The root `nwvue-test/package.json` does not include `run` as a dep or devDep. Since it's obviously needed for this to work, it needs to be added to the template.

Also when doing `npm run build` there is an error of `nwvue-test\node_modules\.bin\build ENOENT`.

**Comment by ghost** [comment]
> The nwvue-test/app/package.json file still contains no deps or devDeps. So whatever you fixed didn't work. And running npm install in the directory won't do anything because of that.

Please give me the errors, I've fixed this, and tested, it was OK!

> Same issue with run not existing running npm run dev. The root nwvue-test/package.json does not include run as a dep or devDep. Since it's obviously needed for this to work, it needs to be added to the template.

> Also when doing npm run build there is an error of nwvue-test\node_modules\.bin\build ENOENT.

Of course it doesn't, the `run` and `build` commands are part of [nwjs-builder-phoenix](https://github.com/evshiron/nwjs-builder-phoenix/), this package is in the devDeps make sure it is installed correctly.

**Comment by TheJaredWilcurt** [comment]
The `run` and `build` are in the `node_modules/.bin` folder, but the same errors still occur, as shown already in the screenshots.

**Comment by sharifzadesina** [comment]
@TheJaredWilcurt what happens when you run them manuly?

**Comment by sharifzadesina** [comment]
@TheJaredWilcurt The issue, is open, I thought you solved the problem sorry.
I've watched the youtube video the problem is same and it is cause of binary files `run` and `build`. so lets test them manually:
First add this to your `<project name>/package.json`:
```
"scripts": {
  "start": "run app"
}
```
Then run `npm run start` in your project root and tell me what happens.

**Comment by ghost** [comment]
@TheJaredWilcurt Test it again and tell me what happens.

**Comment by TheJaredWilcurt** [comment]
![run app](https://user-images.githubusercontent.com/4629794/30249596-611e20a6-960d-11e7-909b-d7b6650a93e0.png)

it pops up NW.js. So that part seems to work. With no local server running, nothing loads (obviously).

**Comment by ghost** [comment]
@TheJaredWilcurt Test it again.

**Comment by TheJaredWilcurt** [comment]
@sharifzadesina 

It works!

The build stuff is still hard coded, so I made a PR to fix that, but everything else works great on Windows.

Closing this, adding it to [Awesome-NWJS](https://github.com/nw-cn/awesome-nwjs)!
